/*******************************************************************************
* Copyright (C) 2015 - 2020 Xilinx, Inc.  All rights reserved.
* SPDX-License-Identifier: GPL-2.0
*******************************************************************************/

#include "xparameters.h"
#include "xvphy.h"

/*
* The configuration table for devices
*/

XVphy_Config XVphy_ConfigTable[XPAR_XVPHY_NUM_INSTANCES] =
{
	{
		XPAR_VID_PHY_CONTROLLER_0_DEVICE_ID,
		XPAR_VID_PHY_CONTROLLER_0_BASEADDR,
		(XVphy_GtType)XPAR_VID_PHY_CONTROLLER_0_TRANSCEIVER,
		XPAR_VID_PHY_CONTROLLER_0_TX_NO_OF_CHANNELS,
		XPAR_VID_PHY_CONTROLLER_0_RX_NO_OF_CHANNELS,
		(XVphy_ProtocolType)XPAR_VID_PHY_CONTROLLER_0_TX_PROTOCOL,
		(XVphy_ProtocolType)XPAR_VID_PHY_CONTROLLER_0_RX_PROTOCOL,
		(XVphy_PllRefClkSelType)XPAR_VID_PHY_CONTROLLER_0_TX_REFCLK_SEL,
		(XVphy_PllRefClkSelType)XPAR_VID_PHY_CONTROLLER_0_RX_REFCLK_SEL,
		(XVphy_SysClkDataSelType)XPAR_VID_PHY_CONTROLLER_0_TX_PLL_SELECTION,
		(XVphy_SysClkDataSelType)XPAR_VID_PHY_CONTROLLER_0_RX_PLL_SELECTION,
		XPAR_VID_PHY_CONTROLLER_0_NIDRU,
		(XVphy_PllRefClkSelType)XPAR_VID_PHY_CONTROLLER_0_NIDRU_REFCLK_SEL,
		(XVidC_PixelsPerClock)XPAR_VID_PHY_CONTROLLER_0_INPUT_PIXELS_PER_CLOCK,
		XPAR_VID_PHY_CONTROLLER_0_TX_BUFFER_BYPASS,
		XPAR_VID_PHY_CONTROLLER_0_HDMI_FAST_SWITCH,
		XPAR_VID_PHY_CONTROLLER_0_TRANSCEIVER_WIDTH,
		XPAR_VID_PHY_CONTROLLER_0_ERR_IRQ_EN,
		XPAR_VID_PHY_CONTROLLER_0_AXI_LITE_FREQ_HZ,
		XPAR_VID_PHY_CONTROLLER_0_DRPCLK_FREQ,
		XPAR_VID_PHY_CONTROLLER_0_USE_GT_CH4_HDMI
	}
};

